# Generated by Django 3.1.4 on 2020-12-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_branch_storeincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='storeincome',
            name='income_month',
            field=models.CharField(max_length=3),
        ),
    ]
